export interface RawHospital {
  name: string;
  address: string;
  city: string;
  voivodeship: string;
  departments: string[];
  department_codes: string[];
  lat: number | null;
  lng: number | null;
}

const baseHospitals: RawHospital[] = [
  // ─── LUBELSKIE ───────────────────────────────────────────────────────────────
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ NR 1 W BEŁŻYCACH",address:"ul. Lubelska 90, 24-200 Bełżyce",city:"Bełżyce",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny Ogólny z Pododdziałem Intensywnej Opieki Pooperacyjnej"],department_codes:["GEN"],lat:51.1736,lng:22.2778},
  {name:"WOJEWÓDZKI SZPITAL SPECJALISTYCZNY W BIAŁEJ PODLASKIEJ",address:"ul. Terebelska 57-65, 21-500 Biała Podlaska",city:"Biała Podlaska",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny","Oddział Neurochirurgiczny","Oddział Urologiczny","Pododdział Chirurgii Onkologicznej"],department_codes:["GEN","NS","URO","ONKO"],lat:52.0324,lng:23.1166},
  {name:"SAMODZIELNY PUBLICZNY WOJEWÓDZKI SZPITAL SPECJALISTYCZNY W CHEŁMIE",address:"ul. Szpitalna 53B, 22-100 Chełm",city:"Chełm",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny z Pododdziałem Laryngologicznym","Oddział Urologiczny"],department_codes:["GEN","URO"],lat:51.1317,lng:23.4716},
  {name:"6 SZPITAL WOJSKOWY Z PRZYCHODNIĄ SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ",address:"ul. Szpitalna 2, 08-530 Dęblin",city:"Dęblin",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:51.5596,lng:21.8453},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ OPIEKI ZDROWOTNEJ W HRUBIESZOWIE",address:"ul. Józefa Piłsudskiego 11, 22-500 Hrubieszów",city:"Hrubieszów",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:50.8053,lng:23.8894},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ ZAKŁADÓW OPIEKI ZDROWOTNEJ W JANOWIE LUBELSKIM",address:"ul. Jana Zamoyskiego 149, 23-300 Janów Lubelski",city:"Janów Lubelski",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:50.7083,lng:22.4167},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ OPIEKI ZDROWOTNEJ W KRASNYMSTAWIE",address:"ul. Głowackiego 3, 22-300 Krasnystaw",city:"Krasnystaw",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny Ogólny","Oddział Urologiczny"],department_codes:["GEN","URO"],lat:50.9833,lng:23.1667},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W KRAŚNIKU",address:"ul. Fryderyka Chopina 13, 23-200 Kraśnik",city:"Kraśnik",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Chirurgii Endoskopowej"],department_codes:["GEN"],lat:50.9244,lng:22.2269},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W LUBARTOWIE",address:"ul. Cicha 14, 21-100 Lubartów",city:"Lubartów",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny Ogólny z Pododdziałem Urologicznym","Oddział Urologiczny"],department_codes:["GEN/URO","URO"],lat:51.4600,lng:22.6094},
  {name:"1 WOJSKOWY SZPITAL KLINICZNY Z POLIKLINIKĄ SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W LUBLINIE",address:"Al. Racławickie 23, 20-904 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej","Oddział Neurochirurgiczny","Oddział Urologiczny"],department_codes:["GEN","NS","URO"],lat:51.2464,lng:22.5320},
  {name:"CENTRUM ONKOLOGII ZIEMI LUBELSKIEJ IM. ŚW. JANA Z DUKLI",address:"ul. Dra Kazimierza Jaczewskiego 7, 20-090 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["I Oddział Chirurgii Onkologicznej","II Oddział Chirurgii Onkologicznej Przewodu Pokarmowego","Oddział Chirurgii Plastycznej","Oddział Urologiczny"],department_codes:["ONKO","PLAST","URO"],lat:51.2389,lng:22.5480},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ MINISTERSTWA SPRAW WEWNĘTRZNYCH I ADMINISTRACJI W LUBLINIE",address:"ul. Grenadierów 3, 20-331 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Urazowo-Ortopedycznym"],department_codes:["GEN"],lat:51.2372,lng:22.5623},
  {name:"UNIWERSYTECKI SZPITAL DZIECIĘCY W LUBLINIE",address:"ul. Prof. Antoniego Gębali 6, 20-093 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Oddział Chirurgii i Traumatologii Dziecięcej"],department_codes:["GEP"],lat:51.2395,lng:22.5510},
  {name:"UNIWERSYTECKI SZPITAL KLINICZNY NR 1 W LUBLINIE",address:"Aleja Solidarności 8, 20-841 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Naczyniowej i Angiologii","Oddział Chirurgii Ogólnej, Gastroenterologicznej i Nowotworów Przewodu Pokarmowego","Oddział Chirurgii Onkologicznej","Oddział Chirurgii Piersi","Oddział Traumatologii"],department_codes:["VAS","GEN","ONKO","PLAST"],lat:51.2289,lng:22.5680},
  {name:"UNIWERSYTECKI SZPITAL KLINICZNY NR 4 W LUBLINIE",address:"ul. Dra Kazimierza Jaczewskiego 8, 20-090 Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Kliniczny Oddział Chirurgii Klatki Piersiowej","Kliniczny Oddział Chirurgii Naczyniowej","Kliniczny Oddział Chirurgii Ogólnej i Leczenia Żywieniowego","Kliniczny Oddział Chirurgii Ogólnej, Plastycznej, Rekonstrukcyjnej i Mikrochirurgii","Kliniczny Oddział Neurochirurgii","Kliniczny Oddział Transplantologii","Kliniczny Oddział Urologii i Onkologii Urologicznej","Kliniczny Oddział Kardiochirurgii"],department_codes:["THS","VAS","GEN","NS","TRANS","URO","CSA"],lat:51.2392,lng:22.5495},
  {name:"WOJEWÓDZKI SZPITAL SPECJALISTYCZNY IM. STEFANA KARDYNAŁA WYSZYŃSKIEGO SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W LUBLINIE",address:"Al. Kraśnicka 100 / ul. Lubartowska 81, Lublin",city:"Lublin",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Naczyniowej","Oddział Chirurgii Piersi","Oddział Neurochirurgii","Oddział Urologii i Onkologii Urologicznej z Centrum Leczenia Kamicy Układu Moczowego","Oddział Chirurgii Ogólnej i Onkologicznej z Pododdziałem Chirurgii Klatki Piersiowej","Oddział Chirurgiczny"],department_codes:["VAS","PLAST","NS","URO","GEN"],lat:51.2270,lng:22.5200},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W ŁĘCZNEJ",address:"ul. Krasnystawska 52, 21-010 Łęczna",city:"Łęczna",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej i Minimalnie Inwazyjnej","Wschodnie Centrum Leczenia Oparzeń i Chirurgii Rekonstrukcyjnej"],department_codes:["GEN","PLAST"],lat:51.3019,lng:22.8808},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W ŁUKOWIE",address:"ul. Dr Andrzeja Rogalińskiego 3, 21-400 Łuków",city:"Łuków",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej i Urazowej"],department_codes:["GEN"],lat:51.9247,lng:22.3789},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W MIĘDZYRZECU PODLASKIM",address:"ul. Warszawska 2-4, 21-560 Międzyrzec Podlaski",city:"Międzyrzec Podlaski",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej i Urazowej"],department_codes:["GEN"],lat:51.9833,lng:22.7833},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W PARCZEWIE",address:"ul. Kościelna 136, 21-200 Parczew",city:"Parczew",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczno-Urazowy z Pododdziałem Ginekologicznym"],department_codes:["GEN"],lat:51.6386,lng:22.9053},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W PUŁAWACH",address:"ul. Bema 1, 24-100 Puławy",city:"Puławy",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej","Oddział Urologii i Onkologii Urologicznej","Oddział Chirurgii Dziecięcej"],department_codes:["GEN","URO","GEP"],lat:51.4167,lng:21.9667},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W RADZYNIU PODLASKIM",address:"ul. Wisznicka 111, 21-300 Radzyń Podlaski",city:"Radzyń Podlaski",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:51.7833,lng:22.6167},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ OPIEKI ZDROWOTNEJ W SZCZEBRZESZYNIE",address:"ul. D-ra Zygmunta Klukowskiego 3, 22-460 Szczebrzeszyn",city:"Szczebrzeszyn",voivodeship:"Lubelskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:50.6944,lng:22.9825},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W ŚWIDNIKU",address:"Aleja Lotników Polskich 18, 21-040 Świdnik",city:"Świdnik",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:51.2222,lng:22.6961},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ OPIEKI ZDROWOTNEJ W TOMASZOWIE LUBELSKIM",address:"Aleje Grunwaldzkie 1, 22-600 Tomaszów Lubelski",city:"Tomaszów Lubelski",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej i Urazowej"],department_codes:["GEN"],lat:50.4478,lng:23.4200},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ OPIEKI ZDROWOTNEJ WE WŁODAWIE",address:"Al. Józefa Piłsudskiego 64, 22-200 Włodawa",city:"Włodawa",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej z Profilem Urazowo-Ortopedycznym i Ginekologicznym"],department_codes:["GEN"],lat:51.5500,lng:23.5500},
  {name:"SAMODZIELNY PUBLICZNY SZPITAL WOJEWÓDZKI IM. PAPIEŻA JANA PAWŁA II W ZAMOŚCIU",address:"Aleje Jana Pawła 10, 22-400 Zamość",city:"Zamość",voivodeship:"Lubelskie",departments:["Oddział Chirurgii Ogólnej i Onkologicznej","Oddział Kardiochirurgii","Oddział Neurochirurgii","Oddział Urologiczny","Oddział Chirurgii Naczyniowej"],department_codes:["GEN","CSA","NS","URO","VAS"],lat:50.7167,lng:23.2528},

  // ─── PODLASKIE ───────────────────────────────────────────────────────────────
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W AUGUSTOWIE",address:"ul. Szpitalna 12, 16-300 Augustów",city:"Augustów",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.8453,lng:22.9803},
  {name:"BIAŁOSTOCKIE CENTRUM ONKOLOGII IM. M. SKŁODOWSKIEJ-CURIE W BIAŁYMSTOKU",address:"ul. Ogrodowa 12, 15-027 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Piersi i Rekonstrukcji","Oddział Urologii"],department_codes:["PLAST","URO"],lat:53.1325,lng:23.1510},
  {name:"NIEPUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ HUMANA MEDICA OMEDA",address:"ul. Fabryczna 39, 15-482 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.1190,lng:23.1780},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ MINISTERSTWA SPRAW WEWNĘTRZNYCH I ADMINISTRACJI W BIAŁYMSTOKU IM. MARIANA ZYNDRAMA-KOŚCIAŁKOWSKIEGO",address:"ul. Fabryczna 27, 15-471 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Onkologicznej i Chirurgii Ogólnej","Oddział Urologii"],department_codes:["GEN/ONKO","URO"],lat:53.1200,lng:23.1760},
  {name:"SP ZOZ WOJEWÓDZKI SZPITAL ZESPOLONY IM. J. ŚNIADECKIEGO",address:"ul. M. Skłodowskiej-Curie 25, 15-950 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej, Małoinwazyjnej i Onkologicznej","Oddział Urologii Onkologicznej i Ogólnej"],department_codes:["GEN","URO"],lat:53.1358,lng:23.1450},
  {name:"UNIWERSYTECKI DZIECIĘCY SZPITAL KLINICZNY IM. L. ZAMENHOFA W BIAŁYMSTOKU",address:"ul. Waszyngtona 17, 15-274 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["Klinika Chirurgii i Urologii Dziecięcej z Pododdziałem Okulistyki Dziecięcej"],department_codes:["GEP/URO"],lat:53.1265,lng:23.1585},
  {name:"UNIWERSYTECKI SZPITAL KLINICZNY W BIAŁYMSTOKU",address:"ul. M.C. Skłodowskiej 24A, 15-276 Białystok",city:"Białystok",voivodeship:"Podlaskie",departments:["I Klinika Chirurgii Ogólnej, Onkologicznej i Endokrynologicznej","I Klinika Nefrologii, Transplantologii i Chorób Wewnętrznych z Ośrodkiem Dializ","II Klinika Chirurgii Ogólnej, Gastroenterologicznej i Onkologicznej","Klinika Chirurgii Klatki Piersiowej","Klinika Chirurgii Naczyń i Transplantacji","Klinika Kardiochirurgii z Blokiem Operacyjnym","Klinika Neurochirurgii","Klinika Urologii i Urologii Onkologicznej"],department_codes:["GEN","TRANS","THS","VAS/TRANS","CSA","NS","URO"],lat:53.1270,lng:23.1570},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W BIELSKU PODLASKIM",address:"ul. Kleszczelowska 1, 17-100 Bielsk Podlaski",city:"Bielsk Podlaski",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny z Pododdziałem Chirurgii Naczyniowej"],department_codes:["GEN"],lat:52.7667,lng:23.1833},
  {name:"SZPITAL OGÓLNY IM. DR WITOLDA GINELA W GRAJEWIE",address:"ul. Konstytucji 3 Maja 34, 19-203 Grajewo",city:"Grajewo",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.6472,lng:22.4500},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W HAJNÓWCE",address:"ul. Doc. Adama Dowgirda 9, 17-200 Hajnówka",city:"Hajnówka",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Laparoskopowej i Klasycznej z Chirurgicznym Leczeniem Otyłości"],department_codes:["GEN"],lat:52.7500,lng:23.5833},
  {name:"SZPITAL OGÓLNY W KOLNIE",address:"ul. Wojska Polskiego 69, 18-500 Kolno",city:"Kolno",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Ortopedii i Traumatologii Narządu Ruchu"],department_codes:["GEN"],lat:53.4167,lng:21.9333},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W ŁAPACH",address:"ul. Korczaka 23, 18-100 Łapy",city:"Łapy",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:52.9833,lng:22.8833},
  {name:"SZPITAL WOJEWÓDZKI IM. KARDYNAŁA STEFANA WYSZYŃSKIEGO W ŁOMŻY",address:"ul. Marsz. Józefa Piłsudskiego 11, 18-404 Łomża",city:"Łomża",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny z Pododdziałem Chirurgii Onkologicznej i Naczyniowej","Oddział Urologii i Urologii Onkologicznej"],department_codes:["GEN","URO"],lat:53.1758,lng:22.0842},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W MOŃKACH",address:"Aleja Niepodległości 9, 19-100 Mońki",city:"Mońki",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny Ogólny z Łóżkami Leczenia Bólu"],department_codes:["GEN"],lat:53.4000,lng:22.8000},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W SEJNACH",address:"ul. Dr Edwarda Rittlera 1, 16-500 Sejny",city:"Sejny",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:54.1117,lng:23.3553},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W SIEMIATYCZACH",address:"ul. Szpitalna 8, 17-300 Siemiatycze",city:"Siemiatycze",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny z Pododdziałem Ortopedycznym"],department_codes:["GEN"],lat:52.4278,lng:22.8611},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W SOKÓŁCE",address:"ul. Gen. Władysława Sikorskiego 40, 16-100 Sokółka",city:"Sokółka",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.4047,lng:23.4978},
  {name:"SZPITAL WOJEWÓDZKI IM. DR. LUDWIKA RYDYGIERA W SUWAŁKACH",address:"ul. Szpitalna 60, 16-400 Suwałki",city:"Suwałki",voivodeship:"Podlaskie",departments:["Oddział Chirurgii Dziecięcej","Oddział Chirurgii Ogólnej z Pododdziałem Chirurgii Onkologicznej","Oddział Urologiczny"],department_codes:["GEP","GEN","URO"],lat:54.1000,lng:22.9333},
  {name:"SZPITAL OGÓLNY W WYSOKIEM MAZOWIECKIEM",address:"ul. Szpitalna 5, 18-200 Wysokie Mazowieckie",city:"Wysokie Mazowieckie",voivodeship:"Podlaskie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:52.9167,lng:22.5167},
  {name:"SZPITAL POWIATOWY W ZAMBROWIE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Papieża J. Pawła II 3, 18-300 Zambrów",city:"Zambrów",voivodeship:"Podlaskie",departments:["Oddział Wieloprofilowy-Zabiegowy"],department_codes:["GEN"],lat:52.9833,lng:22.2500},

  // ─── WARMIŃSKO-MAZURSKIE ─────────────────────────────────────────────────────
  {name:"SZPITAL POWIATOWY IM. JANA PAWŁA II W BARTOSZYCACH",address:"ul. Wyszyńskiego 11, 11-200 Bartoszyce",city:"Bartoszyce",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej i Małoinwazyjnej"],department_codes:["GEN"],lat:54.2536,lng:20.8089},
  {name:"SZPITAL POWIATOWY IM. JANA MIKULICZA W BISKUPCU",address:"ul. Armii Krajowej 8, 11-300 Biskupiec",city:"Biskupiec",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.8667,lng:20.9500},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W DZIAŁDOWIE",address:"ul. Leśna 1, 13-200 Działdowo",city:"Działdowo",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Urologicznym"],department_codes:["GEN/URO"],lat:53.2333,lng:20.1833},
  {name:"SZPITAL MIEJSKI ŚW. JANA PAWŁA II W ELBLĄGU",address:"ul. Komeńskiego 35, 82-300 Elbląg",city:"Elbląg",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej i Onkologicznej","Oddział Chirurgii Dziecięcej"],department_codes:["GEN/ONKO","GEP"],lat:54.1561,lng:19.4044},
  {name:"WOJEWÓDZKI SZPITAL ZESPOLONY W ELBLĄGU",address:"ul. Królewiecka 146, 82-300 Elbląg",city:"Elbląg",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Chirurgii Naczyniowej","Oddział Chirurgii Onkologicznej z Pododdziałem Chirurgii Piersi","Oddział Neurochirurgii, Neurotraumatologii i Chirurgii Kręgosłupa","Oddział Urologiczny"],department_codes:["GEN/VAS","ONKO","NS","URO"],lat:54.1670,lng:19.4200},
  {name:"\"PRO-MEDICA\" W EŁKU SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Baranki 24, 19-300 Ełk",city:"Ełk",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.8233,lng:22.3500},
  {name:"118 SZPITAL WOJSKOWY Z PRZYCHODNIĄ SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W EŁKU",address:"ul. Tadeusza Kościuszki 30, 19-300 Ełk",city:"Ełk",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny Ogólny","Oddział Neurochirurgiczny","Oddział Chirurgii Naczyniowej"],department_codes:["GEN","NS","VAS"],lat:53.8278,lng:22.3603},
  {name:"GIŻYCKA OCHRONA ZDROWIA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Warszawska 41, 11-500 Giżycko",city:"Giżycko",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej","Oddział Urologiczny"],department_codes:["GEN","URO"],lat:54.0389,lng:21.7706},
  {name:"GOLDMEDICA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Słoneczna 7, 19-500 Gołdap",city:"Gołdap",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej-Hospitalizacja Jednodniowa"],department_codes:["GEN"],lat:54.3069,lng:22.3025},
  {name:"POWIATOWY SZPITAL IM. WŁADYSŁAWA BIEGAŃSKIEGO W IŁAWIE",address:"ul. Gen. Władysława Andersa 3, 14-200 Iława",city:"Iława",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:53.5958,lng:19.5672},
  {name:"SZPITAL POWIATOWY W KĘTRZYNIE",address:"ul. M.C. Skłodowskiej 2, 11-400 Kętrzyn",city:"Kętrzyn",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:54.0756,lng:21.3756},
  {name:"SZPITAL MIEJSKI W MORĄGU SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Dąbrowskiego 16, 14-300 Morąg",city:"Morąg",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:53.9167,lng:19.9333},
  {name:"SZPITAL MRĄGOWSKI IM. MICHAŁA KAJKI SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Wolności 3, 11-700 Mrągowo",city:"Mrągowo",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:53.8667,lng:21.3000},
  {name:"ZESPÓŁ OPIEKI ZDROWOTNEJ W NIDZICY",address:"ul. Mickiewicza 25, 13-100 Nidzica",city:"Nidzica",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:53.3592,lng:20.4286},
  {name:"SZPITAL POWIATOWY W NOWYM MIEŚCIE LUBAWSKIM SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Mickiewicza 10, 13-300 Nowe Miasto Lubawskie",city:"Nowe Miasto Lubawskie",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:53.4167,lng:19.5833},
  {name:"\"OLMEDICA W OLECKU - SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ\"",address:"ul. Gołdapska 1, 19-400 Olecko",city:"Olecko",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny"],department_codes:["GEN"],lat:54.0333,lng:22.5000},
  {name:"MIEJSKI SZPITAL ZESPOLONY W OLSZTYNIE",address:"ul. Niepodległości 44, 10-045 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej","Oddział Urologii i Onkologii Urologicznej"],department_codes:["GEN","URO"],lat:53.7756,lng:20.4842},
  {name:"SZPITAL KLINICZNY MINISTERSTWA SPRAW WEWNĘTRZNYCH I ADMINISTRACJI Z WARMIŃSKO-MAZURSKIM CENTRUM ONKOLOGII W OLSZTYNIE",address:"ul. Wojska Polskiego 37, 10-228 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Klinika Chirurgii Onkologicznej","Klinika Urologii i Onkologii Urologicznej","Oddział Kliniczny Chirurgii Ogólnej z Pododdziałem Chorób Piersi"],department_codes:["ONKO","URO","GEN"],lat:53.7850,lng:20.4750},
  {name:"UNIWERSYTECKI SZPITAL KLINICZNY W OLSZNIE",address:"Aleja Warszawska 30, 10-082 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Klinika Chirurgii Onkologicznej i Ogólnej z Pododdziałem Urologicznym","Klinika Neurochirurgii"],department_codes:["ONKO/GEN/URO","NS"],lat:53.7690,lng:20.4700},
  {name:"WARMIŃSKO-MAZURSKIE CENTRUM CHORÓB PŁUC W OLSZTYNIE",address:"ul. Jagiellońska 78, 10-357 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Klatki Piersiowej"],department_codes:["THS"],lat:53.7900,lng:20.5000},
  {name:"WOJEWÓDZKI SPECJALISTYCZNY SZPITAL DZIECIĘCY IM. PROF. DR STANISŁAWA POPOWSKIEGO W OLSZTYNIE",address:"ul. Żołnierska 18A, 10-561 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Kliniczny Chirurgii i Urologii Dziecięcej z Ośrodkiem Leczenia Zmian Naczyniowych"],department_codes:["GEP"],lat:53.7744,lng:20.4960},
  {name:"WOJEWÓDZKI SZPITAL SPECJALISTYCZNY W OLSZTYNIE",address:"ul. Żołnierska 18, 10-561 Olsztyn",city:"Olsztyn",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny Ogólny","Oddział Chirurgii Plastycznej","Oddział Kardiochirurgiczny","Oddział Kliniczny Chirurgii Naczyniowej","Oddział Neurochirurgiczny","Oddział Transplantologiczny"],department_codes:["GEN","PLAST","CSA","VAS","NS","TRANS"],lat:53.7739,lng:20.4950},
  {name:"SZPITAL W OSTRÓDZIE SPÓŁKA AKCYJNA",address:"ul. Jagiełły 1, 14-100 Ostróda",city:"Ostróda",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej z Pododdziałem Urologii"],department_codes:["GEN/URO"],lat:53.6958,lng:19.9694},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ SZPITAL POWIATOWY W PISZU",address:"ul. Sienkiewicza 2, 12-200 Pisz",city:"Pisz",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:53.6281,lng:21.8108},
  {name:"ZESPÓŁ OPIEKI ZDROWOTNEJ W SZCZYTNIE",address:"ul. M.C. Skłodowskiej 12, 12-100 Szczytno",city:"Szczytno",voivodeship:"Warmińsko-Mazurskie",departments:["Oddział Chirurgiczny z Pododdziałem Urazowo-Ortopedycznym"],department_codes:["GEN"],lat:53.5622,lng:20.9869},

  // ─── MAZOWIECKIE ─────────────────────────────────────────────────────────────
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ ZAKŁADÓW OPIEKI ZDROWOTNEJ W ŻUROMINIE",address:"ul. Szpitalna 56, 09-300 Żuromin",city:"Żuromin",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:53.0611,lng:19.8739},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W MŁAWIE",address:"ul. Anny Dobrskiej 1, 06-500 Mława",city:"Mława",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny Ogólny z Pododdziałem Chirurgii Urazowo-Ortopedycznej"],department_codes:["GEN"],lat:53.1122,lng:20.3839},
  {name:"SPECJALISTYCZNY SZPITAL WOJEWÓDZKI W CIECHANOWIE",address:"ul. Powstańców Wielkopolskich 2, 06-400 Ciechanów",city:"Ciechanów",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii Ogólnej, Onkologicznej i Bariatrycznej","Oddział Chirurgii Dziecięcej","Oddział Urologiczny"],department_codes:["GEN/ONKO","GEP","URO"],lat:52.8797,lng:20.6214},
  {name:"SZPITAL POWIATOWY GAJDA-MED SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",address:"ul. Teofila Kwiatkowskiego 19, 06-102 Pułtusk",city:"Pułtusk",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:52.7169,lng:21.0825},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ ZAKŁADÓW OPIEKI ZDROWOTNEJ W PRZASNYSZU",address:"ul. Sadowa 9, 06-300 Przasnysz",city:"Przasnysz",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny","Pododdział Urologiczny"],department_codes:["GEN","URO"],lat:53.0172,lng:20.8850},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ - ZESPÓŁ ZAKŁADÓW W MAKOWIE MAZOWIECKIM",address:"ul. Witosa 2, 06-200 Maków Mazowiecki",city:"Maków Mazowiecki",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:52.8631,lng:21.1019},
  {name:"MAZOWIECKI SZPITAL SPECJALISTYCZNY IM. DR JÓZEFA PSARSKIEGO W OSTROŁĘCE",address:"ul. Jana Pawła II 120A, 07-410 Ostrołęka",city:"Ostrołęka",voivodeship:"Mazowieckie",departments:["Oddział Urologiczny","Pododdział Chirurgii Naczyniowej","Oddział Chirurgii Ogólnej Im Dr Jerzego Olszewskiego","Pododdział Chirurgii Onkologicznej"],department_codes:["URO","VAS","GEN","ONKO"],lat:53.0836,lng:21.5711},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ ZAKŁADÓW OPIEKI ZDROWOTNEJ W OSTROWI MAZOWIECKIEJ",address:"ul. Dubois 68, 07-300 Ostrów Mazowiecka",city:"Ostrów Mazowiecka",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:52.8000,lng:21.8972},
  {name:"SAMODZIELNY PUBLICZNY ZESPÓŁ ZAKŁADÓW OPIEKI ZDROWOTNEJ W WYSZKOWIE",address:"ul. Komisji Edukacji Narodowej 1, 07-200 Wyszków",city:"Wyszków",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:52.5958,lng:21.4578},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W WĘGROWIE",address:"ul. Kościelna 201, 07-100 Węgrów",city:"Węgrów",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:52.3978,lng:22.0186},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W SOKOŁOWIE PODLASKIM",address:"ul. Księdza Jana Bosko 5, 08-300 Sokołów Podlaski",city:"Sokołów Podlaski",voivodeship:"Mazowieckie",departments:["Oddział Chirurgiczny Ogólny"],department_codes:["GEN"],lat:52.4072,lng:22.2486},
  {name:"MAZOWIECKI SZPITAL WOJEWÓDZKI IM. ŚW. JANA PAWŁA II W SIEDLCACH SP. Z O.O.",address:"ul. Poniatowskiego 26, 08-110 Siedlce",city:"Siedlce",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii i Traumatologii Dziecięcej","Oddział Chirurgii Ogólnej i Naczyniowej","Oddział Urologii i Onkologii Urologicznej","Pododdział Chirurgii Naczyniowej","Oddział Chirurgii Onkologicznej","Radiologia","Sterylizatornia","Urologia","Zaopatrzenie (Administracja)"],department_codes:["GEP","GEN","URO","VAS","ONKO","RAD","STER","URO2","ADM"],lat:52.1667,lng:22.2917},
  {name:"SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ W SIEDLCACH",address:"ul. Starowiejska 15, 08-110 Siedlce",city:"Siedlce",voivodeship:"Mazowieckie",departments:["Oddział Chirurgii Ogólnej"],department_codes:["GEN"],lat:52.1700,lng:22.2850},
  {name:"CENTRALNY SZPITAL KLINICZNY MSWIA W WARSZAWIE",address:"ul. Wołoska 137, 02-507 Warszawa",city:"Warszawa",voivodeship:"Mazowieckie",departments:["Chirurgia klatki piersiowej","Kardiochirurgia","Chirurgia naczyniowa"],department_codes:["THS","CSA","VAS"],lat:52.2023,lng:21.0028},
  {name:"UNIWERSYTECKIE CENTRUM KLINICZNE GDAŃSK",address:"ul. Dębinki 7, 80-952 Gdańsk",city:"Gdańsk",voivodeship:"Pomorskie",departments:["Kardiochirurgia","Sterylizatornia","Blok operacyjny","Administracja","Chirurgia klatki piersiowej"],department_codes:["CSA","STER","OR","ADM","THS"],lat:54.3686,lng:18.6294},
];

export const rawHospitals: RawHospital[] = baseHospitals.map(h => {
  const departments = [...h.departments];
  const department_codes = [...h.department_codes];

  const hasOR = departments.some(d => d.toLowerCase() === 'blok operacyjny');
  if (!hasOR) {
    departments.push('Blok operacyjny');
    department_codes.push('OR');
  }

  const hasSter = departments.some(d => d.toLowerCase() === 'sterylizatornia');
  if (!hasSter) {
    departments.push('Sterylizatornia');
    department_codes.push('STER');
  }

  return {
    ...h,
    departments,
    department_codes
  };
});
